"""empty message

Revision ID: 11733092db72
Revises: 5444e6e0d283
Create Date: 2024-11-23 21:21:23.268934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11733092db72'
down_revision: Union[str, None] = '5444e6e0d283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whorehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_id')
    )
    op.drop_constraint('inventory_name_key', 'inventory', type_='unique')
    op.create_unique_constraint(None, 'user_inventory', ['inventory_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_inventory', type_='unique')
    op.create_unique_constraint('inventory_name_key', 'inventory', ['name'])
    op.drop_table('whorehouse')
    # ### end Alembic commands ###
