"""empty message

Revision ID: 240937aaa146
Revises: 860c97cfdc76
Create Date: 2024-11-23 18:48:40.398405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '240937aaa146'
down_revision: Union[str, None] = '860c97cfdc76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inventory_name_key', 'inventory', type_='unique')
    op.create_unique_constraint(None, 'user_inventory', ['inventory_id'])
    op.create_unique_constraint(None, 'whorehouse', ['inventory_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whorehouse', type_='unique')
    op.drop_constraint(None, 'user_inventory', type_='unique')
    op.create_unique_constraint('inventory_name_key', 'inventory', ['name'])
    # ### end Alembic commands ###
