"""empty message

Revision ID: 2faa18786acc
Revises: a1e22545c492
Create Date: 2024-11-23 04:46:32.107939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2faa18786acc'
down_revision: Union[str, None] = 'a1e22545c492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('office_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('floor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'offices', ['office_id'], ['id'])
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'floors', ['floor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'floor_id')
    op.drop_column('users', 'office_id')
    # ### end Alembic commands ###
