"""empty message

Revision ID: a800910d4f1f
Revises: 11733092db72
Create Date: 2024-11-24 09:04:32.130961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a800910d4f1f'
down_revision: Union[str, None] = '11733092db72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_office_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_floor_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'offices', ['office_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'floors', ['floor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_floor_id_fkey', 'users', 'floors', ['floor_id'], ['id'])
    op.create_foreign_key('users_office_id_fkey', 'users', 'offices', ['office_id'], ['id'])
    # ### end Alembic commands ###
