"""empty message

Revision ID: b103a8bca84b
Revises: a800910d4f1f
Create Date: 2024-11-24 09:09:41.659683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b103a8bca84b'
down_revision: Union[str, None] = 'a800910d4f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('floors_office_id_fkey', 'floors', type_='foreignkey')
    op.create_foreign_key(None, 'floors', 'offices', ['office_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'floors', type_='foreignkey')
    op.create_foreign_key('floors_office_id_fkey', 'floors', 'offices', ['office_id'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###
