"""empty message

Revision ID: f6d6d6ccb356
Revises: b103a8bca84b
Create Date: 2024-11-24 09:58:07.428019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d6d6ccb356'
down_revision: Union[str, None] = 'b103a8bca84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('furniture_name_key', 'furniture', type_='unique')
    op.create_unique_constraint(None, 'user_furniture', ['furniture_id'])
    op.add_column('whorehouse', sa.Column('furniture_id', sa.Integer(), nullable=True))
    op.alter_column('whorehouse', 'inventory_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'whorehouse', ['furniture_id'])
    op.create_foreign_key(None, 'whorehouse', 'furniture', ['furniture_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whorehouse', type_='foreignkey')
    op.drop_constraint(None, 'whorehouse', type_='unique')
    op.alter_column('whorehouse', 'inventory_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('whorehouse', 'furniture_id')
    op.drop_constraint(None, 'user_furniture', type_='unique')
    op.create_unique_constraint('furniture_name_key', 'furniture', ['name'])
    # ### end Alembic commands ###
